# Generated by Django 5.2.5 on 2025-08-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargingStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Maintenance"),
                            ("offline", "Offline"),
                            ("defective", "Defective"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "charger_type",
                    models.CharField(
                        choices=[
                            ("type1", "Type 1 (J1772)"),
                            ("type2", "Type 2 (Mennekes)"),
                            ("ccs", "CCS (Combined Charging System)"),
                            ("chademo", "CHAdeMO"),
                            ("tesla", "Tesla Supercharger"),
                        ],
                        max_length=20,
                    ),
                ),
                ("power_rating", models.IntegerField(help_text="Power in kW")),
                ("price_per_kwh", models.DecimalField(decimal_places=3, max_digits=6)),
                ("total_ports", models.IntegerField(default=1)),
                ("available_ports", models.IntegerField(default=1)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "charging_stations",
            },
        ),
        migrations.CreateModel(
            name="StationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="stations.chargingstation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("station", "user")},
            },
        ),
    ]
